### ISSUE TITLE
R9 280 is Not Working (16.04)

### ISSUE THREAD

**Issue by eminfedar** [M-Bab/linux-kernel-amdgpu-binaries#10]
Hi, firstly it is awesome thing, thanks for all your efforts! :+1: 

But I couldn't manage work it, I have:

- R9 280,
- Ubuntu 16.04
- OpenGL version string: 3.0 Mesa 17.1.2
- OpenGL renderer string: Gallium 0.4 on AMD TAHITI (DRM 2.50.0 / 4.11.7+, LLVM 4.0.0)

I just did what you wrote in README, installed .deb packages, and started kernel 4.11.7+, eveything is fine, lspci -v | grep Kernel:
```
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu
```
So I want to use amdgpu and blacklisted radeon in /etc/modprobe.d/blacklist.conf `blacklist radeon`.
Then all of my graphical rendering gone, I ran unity in low graphics mode, then activated radeon again and I can use my gpu now.

How can I use amdgpu? Thanks!

**Comment by eminfedar** [comment]
Here is the news! :
I booted with 4.9.34+ kernel and it worked :+1: 

```
eminfedar@efbuntu:~$ lspci -v | grep amdgpu
	Kernel driver in use: amdgpu
	Kernel modules: radeon, amdgpu
eminfedar@efbuntu:~$ uname -r
4.9.34+
```

**Comment by M-Bab** [comment]
Someone reported it is better to blacklist radeon as boot parameter instead of modprobe:
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/2#issuecomment-296955254

If the 4.9 kernel works for you and you don't need 4.10 or 4.11 features thats fine. After all 4.9 will be maintained longer as a longterm support kernel.

Never forget this kernel is bleeding edge and the GCN 1.0 support is experimental but I am glad when it works for you ;-).

**Comment by M-Bab** [comment]
Is this still an issue or can I close it?
If the problem still exists in 4.11 and you want to help to fix it, it would be great if you figure out which 4.11.X+ kernel version is the last one that actually works. This is possible by installing older 4.11.X+ kernels from the commit history (use git checkout or https://github.com/M-Bab/linux-kernel-amdgpu-binaries/commits/master and the <> button).
Concerning blacklisting radeon: I also thought about just excluding the radeon module from the kernel build via config. But I am not sure if there might be other fatal downsides.

**Comment by eminfedar** [comment]
It didn't work with 4.11.7+ so I can test 8 or directly 9 and write the results here.

**Comment by eminfedar** [comment]
4.11.9+ is not working too :)

**Comment by M-Bab** [comment]
With the newest release you can stop blacklisting the radeon module because it is not built anymore. Can you check if this still results in low graphics mode? If it does can you post your dmesg output after boot or at least the parts of the dmesg output that look relevant?

**Comment by eminfedar** [comment]
It says: (4.11.9+)

```
dmesg | grep amdgpu
[    1.624566] [drm] amdgpu kernel modesetting enabled.
[    1.630047] amdgpu 0000:01:00.0: SI support provided by radeon.
[    1.630048] amdgpu 0000:01:00.0: Use radeon.si_support=0 amdgpu.si_support=1 to override.
```

**Comment by DroWnThePoor** [comment]
I have a custom system with an R9 290x, About to install a distro on it for working with OBS and Video editing. I was thinking of trying Xubuntu 16 and then installing this kernel, any thoughts?

**Comment by M-Bab** [comment]
@eminfedar Well this is a quite direct instruction. "radeon.si_support=0 amdgpu.si_support=1" must be used as kernel parameters to actually enable it (looks like it replaced blacklisting the radeon module in 4.11). However, the most recent kernels should not need that anymore because the radeon module is not build. Can you test it?

@DroWnThePoor Xubuntu is always a solid choice and my personal favorite. If you want maximum graphics performance I recommend to use the latest and not the LTS versions (or any of them when using a PPA providing the latest mesa drivers). The system will run with the included kernel. The kernels here will just add HDMI sound, Freesync and maybe some additional performance.

**Comment by DroWnThePoor** [comment]
What do you mean by: " (or any of them when using a PPA providing the latest mesa drivers).", I don't understand? Also, what are the mesa drivers exactly? There's alot of terminology to understand. What is the difference between gallium,mesa,amdgpu?

Side note: My main computer is a laptop with the FX9800p APU running ElementaryOS Loki on 4.4.0-83-generic with the amdgpu driver, but I have no HDMI audio. I'd like to maximize my performance on that machine as well, do you recommend this repo to do so?

On Thu, Jul 20, 2017 at 2:33 AM, Martin <notifications@github.com> wrote:

@eminfedar<https://github.com/eminfedar> Well this is a quite direct instruction. "radeon.si_support=0 amdgpu.si_support=1" must be used as kernel parameters to actually enable it (looks like it replaced blacklisting the radeon module in 4.11). However, the most recent kernels should not need that anymore because the radeon module is not build. Can you test it?

@DroWnThePoor<https://github.com/drownthepoor> Xubuntu is always a solid choice and my personal favorite. If you want maximum graphics performance I recommend to use the latest and not the LTS versions (or any of them when using a PPA providing the latest mesa drivers). The system will run with the included kernel. The kernels here will just add HDMI sound, Freesync and maybe some additional performance.

**Comment by M-Bab** [comment]
Concerning both systems: Just try it out - it is free to use ;-).

For your other questions I recommend to google them. The Linux graphics stack is complicated and you don't need to understand the details. But if you are still curious read something like this:
https://blogs.igalia.com/itoral/2014/07/29/a-brief-introduction-to-the-linux-graphics-stack/

PPAs are personal package archives for Ubuntu-like systems. Here users can provide packages and updates for easy installations. The PPAs with the most recent mesa are in my Readme. Mesa is the implementation of the graphic interface OpenGL (similar to DirectX on Windows). You don't need this if you only want HDMI audio. You might need this to max out performance of games. Here is a discussion how to add it to ElementaryOS:
https://elementaryos.stackexchange.com/questions/7507/how-can-i-add-a-ppa-in-loki

**Comment by DroWnThePoor** [comment]
Thank you sir, Your the man.
I was actually considering your PPA's when trying to fix my issue before, but someone recently sent me your git
repo and I'm very glad they did. Thanks again.

On Thu, Jul 20, 2017 at 3:01 AM, Martin <notifications@github.com> wrote:

Concerning both systems: Just try it out - it is free to use ;-).

For your other questions I recommend to google them. The Linux graphics stack is complicated and you don't need to understand the details. But if you are still curious read something like this:
https://blogs.igalia.com/itoral/2014/07/29/a-brief-introduction-to-the-linux-graphics-stack/

PPAs are personal package archives for Ubuntu-like systems. Here users can provide packages and updates for easy installations. The PPAs with the most recent mesa are in my Readme. Mesa is the implementation of the graphic interface OpenGL (similar to DirectX on Windows). You don't need this if you only want HDMI audio. You might need this to max out performance of games. Here is a discussion how to add it to ElementaryOS:
https://elementaryos.stackexchange.com/questions/7507/how-can-i-add-a-ppa-in-loki

**Comment by eminfedar** [comment]
Removing the blacklisting of radeon and Adding "radeon.si_support=0 amdgpu.si_support=1" as kernel parameter solved 4.11.9+ issue.

Amdgpu runs now.

**Comment by eminfedar** [comment]
Another problem: I can't open unity-control-center (System Settings), it gives this error:

```
unity-control-center
amdgpu: Unknown family.
Breakdown Failure
```

**Comment by M-Bab** [comment]
Great, nice to hear that.
