### ISSUE TITLE
Cannot build virtualbox when using your kernel

### ISSUE THREAD

**Issue by piet8stevens** [M-Bab/linux-kernel-amdgpu-binaries#14]
I am on Ubuntu 17.04 and used your 4.11.11+ kernel and now upgraded to 4.11.12+. Thank you for all the work.

When I try to upgrade virtualbox to the latest version (5.1.26), I get this error message in /var/log/vbox-install.log: (under both 4.11.11+ and 4.11.12+)
```
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";
```

When I boot the generic 4.10 kernel that comes with 17.04, I can upgrade virtualbox. I suspect I missed source code installation resulting in missing .h  and .conf files.

Note (unrelated to above issue): it is great that 4.11.12+ solved my problem under 4.11.11+ with snap-confine when trying to run any app installed via snap such as vlc or termius (snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks vlc)

**Comment by M-Bab** [comment]
Hi,

That is surprising, I got the file autoconf.h when I install the corresponding linux-header-package. You can check yourself in /usr/src/linux-headers-*VERSION*+/include/generated if the file is actually missing.

Some notes on that:
- You need to install the headers debian package as well or these headers (important for building kernel modules like virtualbox does) are missing
- You should boot the kernel first otherwise some scripts search the wrong paths
- It is always possible that a kernel is to new for some module-building software. Then it won't work anyway.

Did this help?

**Comment by pokebadgerswithspoon** [comment]
I'd like to confirm the issue exist. Let me report some details, probs it will provide a clue for a fix.

The system is running UBUNTU version of the kernel and autoconf.h  exists.
```sh 
$ uname -a
Linux jambo 4.12.8+ #1 SMP Thu Aug 17 19:17:24 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
$ ls -l /usr/src/linux-headers-4.12.8+/include/generated/autoconf.h 
-rw-r--r-- 1 root root 262966 Aug 17 20:14 /usr/src/linux-headers-4.12.8+/include/generated/autoconf.h
```
On start virtualbox complains that /usr/share/libdrm/amdgpu.ids does not exist. And it does not.
```sh 
$ ls /usr/share/libdrm/amdgpu.ids
ls: cannot access '/usr/share/libdrm/amdgpu.ids': No such file or directory
$ ls /usr/share/libdrm
ls: cannot access '/usr/share/libdrm': No such file or directory
```

I've noticed that installing firmware complains on missing hardware.
```sh
$ sudo dpkg -i firmware-radeon-ucode_1.30_all.deb 
(Reading database ... 339679 files and directories currently installed.)
Preparing to unpack firmware-radeon-ucode_1.30_all.deb ...
Unpacking firmware-radeon-ucode (1.30) over (1.30) ...
Setting up firmware-radeon-ucode (1.30) ...
update-initramfs: Generating /boot/initrd.img-4.12.8+
W: Possible missing firmware /lib/firmware/amdgpu/raven_gpu_info.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_rlc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_mec2.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_me.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_pfp.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_ce.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_sdma.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/raven_vcn.bin for module amdgpu
update-initramfs: Generating /boot/initrd.img-4.10.0-32-generic

```

**Comment by M-Bab** [comment]
At first thanks for confirming that autoconf.h exists.

amdgpu.ids is indeed not part of the kernel and it doesn't belong there as well: It is part of the mesa driver (more specifically libdrm-amdgpu package). Unfortunately it is not included in all packages of this type but for example in the ones from Oibaf PPA. Another way is to download it manually and put it there. More information here: https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/24959-updated-and-optimized-ubuntu-free-graphics-drivers?p=961088#post961088

Possibly missing firmwares again is unrelated. This happens when you install the kernel or the firmware package and the kernel includes code for GPUs which are not even released yet (in this case: Raven Ridge). Therefore the firmware blobs are not available yet and not included in my package. Once the blobs are installed by my firmware package these warnings will disappear (as it happened with Vega).

**Comment by pokebadgerswithspoon** [comment]
Its something in between kernel 4.12 in general and virtualbox itself and not related to this particular build.
* virtualbox under 4.9.x series works well.
* virtual box does not work with 4.12 not here, nor in mainline of ubuntu

If someone really wants 4.12 with virtualbox, then he is welcome to toy around with patches, i.e. https://askubuntu.com/a/932894/566479 , for the rest of us there are options to stay with stock kernel or pick 4.9 kernel from this repo if AMDGPU is the goal.

Btw, 4.13 goes fine along with virtualbox. Prbs once it released and merged with  AMD patches it will be all good. I've no idea how merging is done, so putting my hopes on this repo =)

P.s. thnx Martin for the work. Got pretty loading screen and hdmi sound with virtualbox on my updated 4.9 setup!

**Comment by M-Bab** [comment]
I have no clue why so many people combine this kernel with a virtual machine - I mean in this case you have hdmi sound in the host system already(?)

Thanks @pokebadgerswithspoon for pointing out that this is a general problem with the 4.12 kernel. Kernel 4.13 is already on the horizon being released soon and the amd-staging code is also available so this is an option in few weeks. Until then the 4.9 kernel is the only possible solution.
