### ISSUE TITLE
amdgpu_dri.so is missing

### ISSUE THREAD

**Issue by eminfedar** [M-Bab/linux-kernel-amdgpu-binaries#15]
**/usr/lib/x86_64-linux-gnu/dri/amdgpu_dri.so** is missing. How can I solve this?

_/usr/lib/i386-linux-gnu/dri/amdgpu_dri.so exists._

**Comment by M-Bab** [comment]
Why do you miss it? Or what piece of software asks for it?

I don't have any amdgpu_dri.so on my computer and the reason is simple: It is a part of the **amdgpu-pro** driver. It SHOULD not exist anywhere so if you find this file this could mean you have remnants of the amdgpu-pro driver on your system.

**Comment by eminfedar** [comment]
Oh, I've tried installing amdgpu-pro before this so maybe it is about that.

But when I try run a wine game (any game, whether very light simple or very complex) it will not work and give me errors about those type of things.

I guess I should remove my ubuntu and install pure amdgpu + gallium nine to my system :)

**Comment by M-Bab** [comment]
Currently I prefer wine-staging over gallium nine:
https://wine-staging.com/installation.html

Just try if it helps if you create a new wine prefix. By this you don't have to take any risk with your current wine prefix and the effort is minimal.

**Comment by eminfedar** [comment]
Thank you for all of your effort! :)

**Comment by M-Bab** [comment]
So does it work now? :-)
If it does you can close the issue.
