### ISSUE TITLE
The non UBUNTU version of linux-image-4.12* are missing the modules

### ISSUE THREAD

**Issue by jbigot** [M-Bab/linux-kernel-amdgpu-binaries#19]
The archive for `linux-image-4.12.10+_17.08.30.AMDGPU_amd64.deb` (and older) does not contain the `/lib/` directory leading to many problems (missing modules, etc.)

**Comment by M-Bab** [comment]
You are right - that's awful. I have completely missed that since I am only testing/using the Ubuntu variant for quite a while. The issue appears with the first 4.12 kernel - I have to look into this the next days and hopefully re-build it WITH /lib. As first step I removed the faulty kernel and header deb packages.

**Comment by jbigot** [comment]
In any case, thank you for all the great work. Even if I have to keep using your 4.11 kernel, having sound is worth the price!

**Comment by M-Bab** [comment]
Fixed in 4.13+
