### ISSUE TITLE
Debian build?

### ISSUE THREAD

**Issue by shmerl** [M-Bab/linux-kernel-amdgpu-binaries#20]
These packages are targeted for Ubuntu. Should there be any difference for Debian, for example for testing or unstable? And if yes, do you plan to make Debian packages too?

**Comment by M-Bab** [comment]
Thats pretty funny because I removed the most recent "debian" build just yesterday because of https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/19. I guess the Ubuntu variant should still work with Debian - you can just test it.

I WILL add the vanilla kernels without Ubuntu additions again when I resolved the issue. I guess I can combine it with building the 4.13 kernel which will happen this week.

**Comment by M-Bab** [comment]
Now available again with 4.13. It is not specifically debian but simply the vanilla kernel code merged with amd-staging.

The Ubuntu kernel adds the Ubuntu specific kernel changes on top of that.

**Comment by shmerl** [comment]
Does Debian add anything specific too in general?

**Comment by shmerl** [comment]
I just tried installing it, and got this:

```
sudo dpkg -i linux-image-4.13.0+_17.09.06.AMDGPU_amd64.deb linux-headers-4.13.0+_17.09.06.AMDGPU_amd64.deb
dpkg-deb: error: 'linux-image-4.13.0+_17.09.06.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-image-4.13.0+_17.09.06.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-headers-4.13.0+_17.09.06.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-headers-4.13.0+_17.09.06.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 linux-image-4.13.0+_17.09.06.AMDGPU_amd64.deb
 linux-headers-4.13.0+_17.09.06.AMDGPU_amd64.deb
```

**Comment by shmerl** [comment]
I couldn't find your configure commands. Can you post them somewhere in your repo please? It would help analyzing what difference there is between vanilla or other variants to actual distributions.

**Comment by M-Bab** [comment]
I am pretty sure there are Debian specific patches too - but it should also run fine with a vanilla kernel. For Kernel builds there exists no configure command, instead a very large .config file. This is available here https://github.com/M-Bab/linux-kernel-amdgpu for vanilla and Ubuntu kernel but the difference is quite small.

The list of Ubuntu specific patches can be viewed here: http://kernel.ubuntu.com/git/ubuntu/unstable.git/log/?qt=grep&q=UBUNTU%3A - thats all the difference between mbab_4.13 and mbab_4.13_ubuntu.

Did you try out both kernels? Did one of them work with your Debian OS?

**Comment by franglais125** [comment]
@shmerl if you want to see the debian packaging repo, here it is: https://anonscm.debian.org/cgit/kernel/linux.git/tree?h=sid

The patches applied are here, although not all of them apply everywhere: https://anonscm.debian.org/cgit/kernel/linux.git/tree/debian/patches/series?h=sid

Just btw, everywhere I look I see you pop up! be it bugzilla (mozilla), phoronix, git, etc.

**Comment by shmerl** [comment]
@M-Bab: I tried the vanilla build on Debian testing. It works indeed. Just wanted to use something closer to regular Debian build.

@franglais125: Thanks for the pointer! And those places aren't unusual for Linux users.

**Comment by M-Bab** [comment]
Well I will stick to the vanilla and Ubuntu versions of the kernels. The organization of the Debian patches looks a bit more tricky.
But if you like you can head to the source tree (https://github.com/M-Bab/linux-kernel-amdgpu) and try the Debian patches yourself. If you find significant advantages, I will rethink publishing the Debian variant as well.

BTW even the Ubuntu kernel should run on Debian usually. Most of the patches are straight-forward stuff for usability instead of major changes at the kernel itself.
