### ISSUE TITLE
What is the difference between two lines of deb-packages?

### ISSUE THREAD

**Issue by while0pass** [M-Bab/linux-kernel-amdgpu-binaries#38]
Thank you very much for the repository! When I was installing the packages, there was a screen note that /lib/modules had already had 4.14.1+ folder in it. So I finally installed just UBUNTU-variants of the packages and it works like a magic (c) so far.

So you have two variants of headers and image packages:

    /linux-headers-4.14.1+_17.11.23.AMDGPU_amd64.deb
    /linux-image-4.14.1+_17.11.23.AMDGPU_amd64.deb

    /linux-headers-4.14.1+_17.11.23.AMDGPU.UBUNTU_amd64.deb
    /linux-image-4.14.1+_17.11.23.AMDGPU.UBUNTU_amd64.deb

What is the difference between them? If they are not supposed to be installed alongside each other, wouldn't it be better to place them apart in different directories and update the docs?

**Comment by M-Bab** [comment]
It is a bit hidden in the README:
Added new fancy kernel: .UBUNTU uses the 4.11 kernel in the artful repo and merges the amd-staging stuff. Therefore all custom Ubuntu patches (UBUNTU: SAUCE) are included. This might be the best kernel for Ubuntu systems. The other two kernels remain on the codebase of the vanilla kernel + amd-staging.

For Ubuntu the Ubuntu-variant is better, for Debian or similar the vanilla- variant. I was not aware of this collision but won't change the repo structure anymore since it will be most likely obsolete when 4.15 is released.
