### ISSUE TITLE
_UBUNTU kernels starting to lag behind on updates?

### ISSUE THREAD

**Issue by lillelilje** [M-Bab/linux-kernel-amdgpu-binaries#62]
Hi!
I'm wondering why the _UBUNTU kernels are now starting to lag behind on updates.

**Comment by M-Bab** [comment]
Hi! Ubuntu unstable jumped on to the 4.17 kernel while amd-staging-drm-next is still 4.16. And the code base started to diverge so heavily that I was not able to merge it properly anymore. And instead of risking to produce a crappy kernel I stopped updating it.

Once amd-staging-drm-next jumps to the next mainline I will pick it up again.

**Comment by lillelilje** [comment]
Thank you! :)
