### ISSUE TITLE
Two Vulkan devices showing up after install

### ISSUE THREAD

**Issue by Grant12311** [M-Bab/linux-kernel-amdgpu-binaries#96]
Hello. Yesterday while setting up my new PC (running POP OS) I noticed that my OpenGL drivers only supported up to OpenGL 4.5, not the 4.6 that my GPU had previously been capable of. So I follow your install instructions everything seems to be working as expected, except that I now have a second Vulkan device showing up. Attached is the output from vulkaninfo. Was I supposed to uninstall the GPU drivers I already had installed before installing your kernel?
[info.txt](https://github.com/M-Bab/linux-kernel-amdgpu-binaries/files/6305264/info.txt)

**Comment by Grant12311** [comment]
I have discovered something else that's interesting. I use this program for fan control but it no longer works after installing the new drivers https://github.com/marazmista/radeon-profile. Most fields and buttons are disabled or empty.

**Comment by M-Bab** [comment]
Well the driver world is a bit complicated in Linux. What you definitely should NOT have installed is the proprietary driver from AMD "amdgpu pro". This thing here: https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-45

This is in simple conflict with the driver in this kernel. What also conflicts is the old "radeon" driver - but because this also comes out of the kernel, I disabled it in this kernel. This kernel is about the open source amdgpu driver only.

When you have this driver you can run the GPU but you still need MESA to do things like OpenGL, video acceleration, Vulkan. Usually they are already installed on Linux.

For Direct 3D (Windows) the Wine emulation has the answers: Direct 3D can be translated to OpenGL, or to Vulkan or there is an API translating it directly.

Also with the open source driver you can read temperatures and fan speeds. Here is my output from sensors:

```
amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:      937.00 mV 
fan1:         851 RPM  (min =    0 RPM, max = 6000 RPM)
edge:         +66.0°C  (crit = +104.0°C, hyst = -273.1°C)
power1:       25.20 W  (cap = 150.00 W)
```
